=== joethompson1/Stendhal_TeamProject/data/conf/achievements.xsd
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="stendhal"
	xmlns:tns="http://www.example.org/zones" elementFormDefault="qualified"
	xmlns:Q1="stendhal">

	<element name="achievements" type="Q1:achievementGroup"></element>

	<complexType name="achievementGroup">
		<sequence>
			<element name="achievement" type="Q1:achievementType" minOccurs="0"
				maxOccurs="unbounded"></element>
		</sequence>
	</complexType>

	<complexType name="achievementType">
		<sequence>
			<element name="title" type="string"></element>
			<element name="description" type="string"></element>
			<element name="score" type="Q1:score"></element>
			<element name="active" type="string" ></element>
			<element name="conditions" type="Q1:conditions"></element>
		</sequence>
		<attribute name="identifier" type="string" use="required"></attribute>
	</complexType>

    <complexType name="score"
		<attribute name="value" type="integer"></attribute>
	</complexType>

	<complexType name="conditions"
	    <sequence>
			<element name="classname" minOccurs="0" maxOccurs="unbounded"></element>
			<element name="param" minOccurs="0" maxOccurs="unbounded"></element>
		</sequence>
		<attribute name="value" type="string"></attribute>
	</complexType>

</schema>

=== joethompson1/Stendhal_TeamProject/data/conf/achievements/adositemquestachievements.xml
<?xml version="1.0" encoding="UTF-8"?>
<achievements xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../achievements.xsd ">
  
  <achievement identifier="quest.special.daily_item.0010">
	<title>Ados' Supporter</title>
	<description>Finish daily item quest 10 times</description>
	<score value="1"></score>
	<active value="true"></active>
	<conditions>
	  <classname value="QuestStateGreaterThanCondition"></classname>
	  <param value="daily_item"></param>
	  <param value="2"></param>
	  <param value="9"></param>
	</conditions>
   </achievement>
   
   <achievement identifier="quest.special.daily_item.0087">
	<title>Ados' Supporter</title>
	<description>Finish daily item quest 10 times</description>
	<score value="1"></score>
	<active value="true"></active>
	<conditions>
	  <classname value="QuestStateGreaterThanCondition"></classname>
	  <param value="daily_item"></param>
	  <param value="2"></param>
	  <param value="9"></param>
	</conditions>
   </achievement>
  
</achievements>

<!--

  <achievement identifier="quest.special.daily_item.0010">
    <title>Ados' Supporter</title>
    <description>Finish daily item quest 10 times</description>
    <score value="1"></score>
    <active>true</active>
    <conditions>
    	<class value="QuestStateGreaterThanCondition"></class>
    		<param value="daily_item" type="String"?></param>
    		<param value="2" type="int"?></param>
    		<param value="9" type="int"?></param>
    </conditions>
  </achievements>
  
  <achievement identifier="quest.special.daily_item.0050">
    <title>Ados' Provider</title>
    <description>Finish daily item quest 50 times</description>
    <score value="1"></score>
    <active>true</active>
    <conditions>
    	<class value="QuestStateGreaterThanCondition"></class>
    		<param value="daily_item" type="String"?></param>
    		<param value="2" type="int"?></param>
    		<param value="49" type="int"?></param>
    </conditions>
  </achievements>
  
  <achievement identifier="quest.special.daily_item.0100">
    <title>Ados' Supplier</title>
    <description>Finish daily item quest 100 times</description>
    <score value="2"></score>
    <active>true</active>
    <conditions>
    	<class value="QuestStateGreaterThanCondition"></class>
    		<param value="daily_item" type="String"?></param>
    		<param value="2" type="int"?></param>
    		<param value="99" type="int"?></param>
    </conditions>
  </achievements>
  
  <achievement identifier="quest.special.daily_item.0250">
    <title>Ados' Stockpiler</title>
    <description>Finish daily item quest 250 times</description>
    <score value="2"></score>
    <active>true</active>
    <conditions>
    	<class value="QuestStateGreaterThanCondition"></class>
    		<param value="daily_item" type="String"?></param>
    		<param value="2" type="int"?></param>
    		<param value="249" type="int"?></param>
    </conditions>
  </achievements>
  
  <achievement identifier="quest.special.daily_item.0500">
    <title>Ados' Hoarder</title>
    <description>Finish daily item quest 500 times</description>
    <score value="5"></score>
    <active>true</active>
    <conditions>
    	<class value="QuestStateGreaterThanCondition"></class>
    		<param value="daily_item" type="String"?></param>
    		<param value="2" type="int"?></param>
    		<param value="499" type="int"?></param>
    </conditions>
  </achievements>
  
</achievements>

-->

=== joethompson1/Stendhal_TeamProject/data/conf/achievements/outsidezoneachievement.xml
<?xml version="1.0" encoding="UTF-8"?>
<achievements xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../achievements.xsd ">

  <achievement identifier="zone.outside.semos">
    <title>Junior Explorer</title>
    <description>Visit all outside zones in the Semos region</description>
    <score value="1"></score>
    <active value = "true" ></active>
    <conditions>
    	<classname value ="PlayerVisitedZonesInRegionCondition"</classname>
    		<param value="semos"?></value>
    		<param value="true"?></value>
    		<param value="true"?></value>
    </conditions>
  </achievement>

  <achievement identifier="zone.outside.ados">
    <title>Big City Explorer</title>
    <description>Visit all outside zones in the Ados region</description>
    <score value="1"></score>
    <active value = "true" ></active>
    <conditions>
    	<classname value ="PlayerVisitedZonesInRegionCondition"</classname>
    		<param value="ados"?></value>
    		<param value="true"?></value>
    		<param value="true"?></value>
    </conditions>
  </achievement>
  
  <achievement identifier="zone.outside.fado">
    <title>Far South</title>
    <description>Visit all outside zones in the Fado region</description>
    <score value="1"></score>
    <active value = "true" ></active>
    <conditions>
    	<classname value ="PlayerVisitedZonesInRegionCondition"</classname>
    		<param value="fado"?></value>
    		<param value="true"?></value>
    		<param value="true"?></value>
    </conditions>
  </achievement>
  
  <achievement identifier="zone.outside.orril">
    <title>Scout</title>
    <description>Visit all outside zones in the Orril region</description>
    <score value="1"></score>
    <active value = "true" ></active>
    <conditions>
    	<classname value ="PlayerVisitedZonesInRegionCondition"</classname>
    		<param value="orril"?></value>
    		<param value="true"?></value>
    		<param value="true"?></value>
    </conditions>
  </achievement>
  
  <achievement identifier="zone.outside.amazon">
    <title>Jungle Explorer</title>
    <description>Visit all outside zones in the Amazon region</description>
    <score value="1"></score>
    <active value = "true" ></active>
    <conditions>
    	<classname value ="PlayerVisitedZonesInRegionCondition"</classname>
    		<param value="amazon"?></value>
    		<param value="true"?></value>
    		<param value="true"?></value>
    </conditions>
  </achievement>
  
  <achievement identifier="zone.outside.athor">
    <title>Tourist</title>
    <description>Visit all outside zones in the Athor region</description>
    <score value="1"></score>
    <active value = "true" ></active>
    <conditions>
    	<classname value ="PlayerVisitedZonesInRegionCondition"</classname>
    		<param value="athor"?></value>
    		<param value="true"?></value>
    		<param value="true"?></value>
    </conditions>
  </achievement>
  
  <achievement identifier="zone.outside.kikareukin">
    <title>Sky Tower</title>
    <description>Visit all outside zones in the Kikareukin region</description>
    <score value="1"></score>
    <active value = "true" ></active>
    <conditions>
    	<classname value ="PlayerVisitedZonesInRegionCondition"</classname>
    		<param value="kikareukin"?></value>
    		<param value="true"?></value>
    		<param value="true"?></value>
    </conditions>
  </achievement>
  
  <achievement identifier="zone.special.bank">
    <title>Safe Deposit</title>
    <description>Visit all banks</description>
    <score value="2"></score>
    <active value = "true" ></active>
    <conditions>
    	<classname value ="PlayerVisitedZonesInRegionCondition"</classname>
    		<param value="int_semos_bank"?></value>
    		<param value="int_nalwor_bank"?></value>
    		<param value="int_kirdneh_bank"?></value>
    		<param value="int_fado_bank"?></value>
    		<param value="int_magic_bank"?></value>
    		<param value="int_ados_bank"?></value>
    </conditions>
  </achievement>

  
</achievements>

=== joethompson1/Stendhal_TeamProject/data/conf/achievements/kirdnehitemachievements.xml
<?xml version="1.0" encoding="UTF-8"?>
<achievements xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../achievements.xsd ">

  <achievement identifier=quest.special.weekly_item.0005">
    <title>Archaeologist</title>
    <description>Finish weekly item quest 5 times</description>
    <score value="5"></score>
    <active value = "true" ></active>
    <conditions>
    	<classname value ="QuestStateGreaterThanCondition"</classname>
    		<param value="weekly_item"?></value>
    		<param value="2"?></value>
    		<param value="4"?></value>
    </conditions>
  </achievement>
  
  <achievement identifier=quest.special.weekly_item.0025">
    <title> Dedicated Archaeologist</title>
    <description>Finish weekly item quest 25 times</description>
    <score value="5"></score>
    <active value = "true" ></active>
    <conditions>
    	<classname value ="QuestStateGreaterThanCondition"</classname>
    		<param value="weekly_item"?></value>
    		<param value="2"?></value>
    		<param value="24"?></value>
    </conditions>
  </achievement>
  
  <achievement identifier=quest.special.weekly_item.0050">
    <title>Senior Archaeologist</title>
    <description>Finish weekly item quest 50 times</description>
    <score value="5"></score>
    <active value = "true" ></active>
    <conditions>
    	<classname value ="QuestStateGreaterThanCondition"</classname>
    		<param value="weekly_item"?></value>
    		<param value="2"?></value>
    		<param value="49"?></value>
    </conditions>
  </achievement>

  <achievement identifier=quest.special.weekly_item.0100">
    <title>Master Archaeologist</title>
    <description>Finish weekly item quest 100 times</description>
    <score value="5"></score>
    <active value = "true" ></active>
    <conditions>
    	<classname value ="QuestStateGreaterThanCondition"</classname>
    		<param value="weekly_item"?></value>
    		<param value="2"?></value>
    		<param value="99"?></value>
    </conditions>
  </achievement>
  
</achievements>

=== joethompson1/Stendhal_TeamProject/data/conf/achievements/itemachievements.xml
<?xml version="1.0" encoding="UTF-8"?>
<achievements xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../achievements.xsd ">

  <achievement identifier="item.money.100">
    <title>First pocket money</title>
    <description>Loot 100 money from creatures</description>
    <score value="1"></score>
    <active>true</active>
    <conditions>
    	<classname value="PlayerLootedNumberOfItemsCondition"></class>
    	<param value="100"?></param>
    	<param value="money"?></param>
    </conditions>
  </achievement>
  
  <achievement identifier="item.money.1000000">
    <title>You don't need it anymore</title>
    <description>Loot 1000000 money from creatures</description>
    <score value="5"></score>
    <active>true></active>
    <conditions>
    	<classname value="PlayerLootedNumberOfItemsCondition"></class>
    	<param value="1000000"?></param>
    	<param value="money"?></param>
    </conditions>
  </achievement>
  
  <achievement identifier="item.set.red">
    <title>Amazon's Menace</title>
    <description>Loot a complete red equipment set</description>
    <score value="2"></score>
    <active>true></active>
    <conditions>
    	<classname value="PlayerLootedNumberOfItemsCondition"></class>
    	<param value="1" ?></param>
    	<param value="red armor"?></param>
    	<param value="red helmet"?></param>
    	<param value="red cloak"?></param>
    	<param value="red legs""?></param>
    	<param value="red boots"?></param>
    	<param value="red shield"?></param>
    </conditions>
  </achievement>
  
  <achievement identifier="item.set.blue">
    <title>Feeling Blue</title>
    <description>Loot a complete blue equipment set</description>
    <score value="2"></score>
    <active>true></active>
    <conditions>
    	<classname value="PlayerLootedNumberOfItemsCondition"></class>
    	<param value="1"?></param>
    	<param value="blue armor"?></param>
    	<param value="blue helmet"?></param>
    	<param value="blue striped cloak"?></param>
    	<param value="blue legs"?></param>
    	<param value="blue boots"?></param>
    	<param value="blue shield"?></param>
    </conditions>
  </achievement>
  
  <achievement identifier="item.set.elvish">
    <title>Nalwor's Bane</title>
    <description>Loot a complete elvish equipment set</description>
    <score value="2"></score>
    <active>true></active>
    <conditions>
    	<classname value="PlayerLootedNumberOfItemsCondition"></class>
    	<param value="1"?></param>
    	<param value="elvish armor"?></param>
    	<param value="elvish hat"?></param>
    	<param value="elvish cloak"?></param>
    	<param value="elvish legs"?></param>
    	<param value="elvish boots"?></param>
    	<param value="elvish shield"?></param>
    </conditions>
  </achievement>
  
  <achievement identifier="item.set.shadow">
    <title>Shadow Dweller</title>
    <description>Loot a complete shadow equipment set</description>
    <score value="2"></score>
    <active>true></active>
    <conditions>
    	<classname value="PlayerLootedNumberOfItemsCondition"></class>
    	<param value="1"?></param>
    	<param value="shadow armor"?></param>
    	<param value="shadow helmet"?></param>
    	<param value="shadow cloak"?></param>
    	<param value="shadow legs"?></param>
    	<param value="shadow boots"?></param>
    	<param value="shadow shield"?></param>
    </conditions>
  </achievement>
  
  <achievement identifier="item.set.chaos">
    <title>Chaotic Looter</title>
    <description>Loot a complete chaos equipment set</description>
    <score value="5"></score>
    <active>true></active>
    <conditions>
    	<classname value="PlayerLootedNumberOfItemsCondition"></class>
    	<param value="1"?></param>
    	<param value="chaos armor"?></param>
    	<param value="chaos helmet"?></param>
    	<param value="chaos cloak"?></param>
    	<param value="chaos legs"?></param>
    	<param value="chaos boots"?></param>
    	<param value="chaos shield"?></param>
    </conditions>
  </achievement>
  
  <achievement identifier="item.set.golden">
    <title>Golden Boy</title>
    <description>Loot a complete golden equipment set</description>
    <score value="2"></score>
    <active>true></active>
    <conditions>
    	<classname value="PlayerLootedNumberOfItemsCondition"></class>
    		<param value="1"?></param>
    		<param value="golden armor"?></param>
    		<param value="golden helmet"?></param>
    		<param value="golden cloak"?></param>
    		<param value="golden legs"?></param>
    		<param value="golden boots"?></param>
    		<param value="golden shield"?></param>
    </conditions>
  </achievement>
  
  <achievement identifier="item.set.black">
    <title>Come to the dark side</title>
    <description>Loot a complete black equipment set</description>
    <score value="5"></score>
    <active value="true"></active>
    <conditions>
    	<classname value="PlayerLootedNumberOfItemsCondition"></class>
    		<param value="1"?></param>
    		<param value="black armor"?></param>
    		<param value="black helmet"?></param>
    		<param value="black cloak"?></param>
    		<param value="black legs"?></param>
    		<param value="black boots"?></param>
    		<param value="black shield"?></param>
    </conditions>
  </achievement>
  
  <achievement identifier="item.set.mainio">
    <title>Excellent Stuff</title>
    <description>Loot a complete mainio equipment set</description>
    <score value="5"></score>
    <active value="true"></active>
    <conditions>
    	<classname value="PlayerLootedNumberOfItemsCondition"></class>
    		<param value="1"?></param>
    		<param value="mainio armor"?></param>
    		<param value="mainio helmet"?></param>
    		<param value="mainio cloak"?></param>
    		<param value="mainio legs"?></param>
    		<param value="mainio boots"?></param>
    		<param value="mainio shield"?></param>
    </conditions>
  </achievement>
  
  <achievement identifier="item.set.xeno">
    <title>A Bit Xenophobic?</title>
    <description>Loot a complete xeno equipment set</description>
    <score value="5"></score>
    <active value="true"></active>
    <conditions>
    	<classname value="PlayerLootedNumberOfItemsCondition"></class>
    		<param value="1"?></param>
    		<param value="xeno armor"?></param>
    		<param value="xeno helmet"?></param>
    		<param value="xeno cloak"?></param>
    		<param value="xeno legs"?></param>
    		<param value="xeno boots"?></param>
    		<param value="xeno shield"?></param>
    </conditions>
  </achievement>
  
  <achievement identifier="item.cloak.dragon">
    <title>Dragon Slayer</title>
    <description>Loot all dragon cloaks</description>
    <score value="2"></score>
    <active value="true"></active>
    <conditions>
    	<classname value="PlayerLootedNumberOfItemsCondition"></class>
    		<param value="1" ?></param>
    		<param value="black dragon cloak"?></param>
    		<param value="blue dragon cloak"?></param>
    		<param value="bone dragon cloak"?></param>
    		<param value="green dragon cloak"?></param>
    		<param value="red dragon cloak"?></param>
    </conditions>
  </achievement>
  
</achievements>

=== joethompson1/Stendhal_TeamProject/data/conf/achievements/undergroundzoneachievements.xml
<?xml version="1.0" encoding="UTF-8"?>
<achievements xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../achievements.xsd ">
	
	
	<achievement identifier="zone.underground.semos">
	<title>Canary</title>
	<description>Visit all underground zones in the Semos region</description>
	<score value="3"></score>
	<active value="true"></active>
	<conditions>
	  <classname value="PlayerVisitedZonesInRegionCondition"></classname>
	  <param value="semos"></param>
	  <param value="true"></param>
	  <param value="false"></param>
	</conditions>
   </achievement>
   
	<achievement identifier="zone.underground.nalwor">
	<title>Fear not drows nor hell</title>
	<description>Visit all underground zones in the Nalwor region</description>
	<score value="3"></score>
	<active value="true"></active>
	<conditions>
	  <classname value="PlayerVisitedZonesInRegionCondition"></classname>
	  <param value="nalwor"></param>
	  <param value="true"></param>
	  <param value="false"></param>
	</conditions>
   </achievement>

	<achievement identifier="zone.underground.athor">
	<title>Canary</title>
	<description>Visit all underground zones in the athor region</description>
	<score value="3"></score>
	<active value="true"></active>
	<conditions>
	  <classname value="PlayerVisitedZonesInRegionCondition"></classname>
	  <param value="athor"></param>
	  <param value="true"></param>
	  <param value="false"></param>
	</conditions>
   </achievement>
   
	<achievement identifier="zone.underground.amazon">
	<title>Canary</title>
	<description>Visit all underground zones in the amazon region</description>
	<score value="3"></score>
	<active value="true"></active>
	<conditions>
	  <classname value="PlayerVisitedZonesInRegionCondition"></classname>
	  <param value="amazon"></param>
	  <param value="true"></param>
	  <param value="false"></param>
	</conditions>
   </achievement>
   
	<achievement identifier="zone.underground.ados">
	<title>Canary</title>
	<description>Visit all underground zones in the ados region</description>
	<score value="3"></score>
	<active value="true"></active>
	<conditions>
	  <classname value="PlayerVisitedZonesInRegionCondition"></classname>
	  <param value="ados"></param>
	  <param value="true"></param>
	  <param value="false"></param>
	</conditions>
   </achievement>
	
	
	
</achievements>

=== joethompson1/Stendhal_TeamProject/data/conf/achievements/interiorzoneachievements.xml
<?xml version="1.0" encoding="UTF-8"?>
<achievements xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../achievements.xsd ">

  <achievement identifier="zone.interior.semos">
	<title>Home maker</title>
	<description>Visit all interior zones in the Semos region</description>
	<score value="3"></score>
	<active value="true"></active>
	<conditions>
	  <classname value="PlayerVisitedZonesInRegionCondition"></classname>
	  <param value="semos"></param>
	  <param value="false"></param>
	  <param value="false"></param>
	</conditions>
   </achievement>

  <achievement identifier="zone.interior.nalwor">
	<title>Elf visitor</title>
	<description>Visit all interior zones in the Nalwor region</description>
	<score value="3"></score>
	<active value="true"></active>
	<conditions>
	  <classname value="PlayerVisitedZonesInRegionCondition"></classname>
	  <param value="nalwor"></param>
	  <param value="false"></param>
	  <param value="false"></param>
	</conditions>
   </achievement>
   
     <achievement identifier="zone.interior.ados">
	<title>Up town guy</title>
	<description>Visit all accessible interior zones in the Ados region</description>
	<score value="3"></score>
	<active value="true"></active>
	<conditions>
	  <classname value="PlayerVisitedZonesInRegionCondition"></classname>
	  <param value="ados"></param>
	  <param value="false"></param>
	  <param value="false"></param>
	</conditions>
   </achievement>
   
     <achievement identifier="zone.interior.wofolcity">
	<title>Kobold City</title>
	<description>Visit all interior zones in Wo'fol</description>
	<score value="3"></score>
	<active value="true"></active>
	<conditions>
	  <classname value="PlayerVisitedZonesInRegionCondition"></classname>
	  <param value="wofol city"></param>
	  <param value="false"></param>
	  <param value="false"></param>
	</conditions>
   </achievement>
   
     <achievement identifier="zone.interior.magiccity">
	<title>Magic City</title>
	<description>Visit all interior zones in the underground Magic city</description>
	<score value="3"></score>
	<active value="true"></active>
	<conditions>
	  <classname value="PlayerVisitedZonesInRegionCondition"></classname>
	  <param value="magic city"></param>
	  <param value="false"></param>
	  <param value="false"></param>
	</conditions>
   </achievement>

</achievements>

=== joethompson1/Stendhal_TeamProject/data/conf/achievements/experienceachievements.xml
<?xml version="1.0" encoding="UTF-8"?>
<achievements xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../achievements.xsd ">

  <achievement identifier="xp.level.010">
    <title>Greenhorn</title>
    <description>Reach level 10</description>
    <score value="1"></score>
    <active value = "true" ></active>
    <conditions>
    	<classname value ="LevelGreaterThanCondition"></classname>
    		<param value="9"?></value>
    </conditions>
  </achievement>
  
  <achievement identifier="xp.level.050">
    <title>Novice</title>
    <description>Reach level 50</description>
    <score value="1"></score>
    <active value = "true" ></active>
    <conditions>
    	<classname value ="LevelGreaterThanCondition"></classname>
    		<param value="49"?></value>
    </conditions>
  </achievement>
  
  <achievement identifier="xp.level.100">
    <title>Apprentice</title>
    <description>Reach level 100</description>
    <score value="1"></score>
    <active value = "true" ></active>
    <conditions>
    	<classname value ="LevelGreaterThanCondition"></classname>
    		<param value="99"?></value>
    </conditions>
  </achievement>

  <achievement identifier="xp.level.200">
    <title>Adventurer</title>
    <description>Reach level 200</description>
    <score value="2"></score>
    <active value = "true" ></active>
    <conditions>
    	<classname value ="LevelGreaterThanCondition"></classname>
    		<param value="199"?></value>
    </conditions>
  </achievement>
  
  <achievement identifier="xp.level.300">
    <title>Experienced Adventurer</title>
    <description>Reach level 300</description>
    <score value="2"></score>
    <active value = "true" ></active>
    <conditions>
    	<classname value ="LevelGreaterThanCondition"></classname>
    		<param value="299"?></value>
    </conditions>
  </achievement>

  <achievement identifier="xp.level.400">
    <title>Master Adventurer</title>
    <description>Reach level 400</description>
    <score value="2"></score>
    <active value = "true" ></active>
    <conditions>
    	<classname value ="LevelGreaterThanCondition"></classname>
    		<param value="399"?></value>
    </conditions>
  </achievement>
  
  <achievement identifier="xp.level.500">
    <title>Stendhal Master</title>
    <description>Reach level 500</description>
    <score value="5"></score>
    <active value = "true" ></active>
    <conditions>
    	<classname value ="LevelGreaterThanCondition"?></classname>
    		<param value="499"?></value>
    </conditions>
  </achievement>

  <achievement identifier="xp.level.597">
    <title>Stenhal High Master</title>
    <description>Reach level 597</description>
    <score value="5"></score>
    <active value = "true"></active>
    <conditions>
    	<classname value ="LevelGreaterThanCondition"></classname>
    		<param value="596"?></value>
    </conditions>
  </achievement>
  
</achievements>

=== joethompson1/Stendhal_TeamProject/data/conf/achievements/questachievements.xml
<?xml version="1.0" encoding="UTF-8"?>
<achievements xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../achievements.xsd ">

  <achievement identifier="quest.special.elf_princess.0025">
    <title>Faiumoni's Casanova</title>
    <description>Finish elf princess quest 25 times</description>
    <score value="2"></score>
    <active value = "true" ></active>
    <conditions>
    	<classname value ="QuestStateGreaterThanCondition"</classname>
    		<param value="elf_princess"?></value>
    		<param value="2"?></value>
    		<param value="24"?></value>
    </conditions>
  </achievement>

  <achievement identifier="quest.special.kill_monks.0025">
    <title>Heretic</title>
    <description>Finish Kill Monks quest 25 times</description>
    <score value="5"></score>
    <active value = "true" ></active>
    <conditions>
    	<classname value ="QuestStateGreaterThanCondition"</classname>
    		<param value="kill_monks"?></value>
    		<param value="2"?></value>
    		<param value="24"?></value>
    </conditions>
  </achievement>
  
  <achievement identifier="quest.special.maze">
    <title>Pathfinder</title>
    <description>Finish the maze</description>
    <score value="1"></score>
    <active value = "true" ></active>
    <conditions>
    	<classname value ="QuestStateGreaterThanCondition"</classname>
    		<param value="maze"?></value>
    		<param value="2"?></value>
    		<param value="0"?></value>
    </conditions>
  </achievement>
  
  <achievement identifier="quest.deathmatch">
    <title>Deathmatch Hero</title>
    <description>Earn 100,000 points in deathmatch</description>
    <score value="2"></score>
    <active value = "true" ></active>
    <conditions>
    	<classname value ="QuestStateGreaterThanCondition"</classname>
    		<param value="deathmatch_score"?></value>
    		<param value="0"?></value>
    		<param value="100000"?></value>
    </conditions>
  </achievement>
  
  <achievement identifier="quest.special.semos">
    <title>Aide to Semos folk</title>
    <description>Complete all quests in Semos City</description>
    <score value="2"></score>
    <active value = "true" ></active>
    <conditions>
    	<classname value ="QuestsInRegionCompletedCondition"</classname>
    		<param value="Semos City"?></value>
    </conditions>
  </achievement>
  
  <achievement identifier="quest.special.ados">
    <title>Helper of Ados city dwellers</title>
    <description>Complete all quests in Ados City</description>
    <score value="2"></score>
    <active value = "true" ></active>
    <conditions>
    	<classname value ="QuestsInRegionCompletedCondition"</classname>
    		<param value="Ados City"?></value>
    </conditions>
  </achievement>
  
  <achievement identifier="quest.count.80">
    <title>Quest Junkie</title>
    <description>Complete at least 80 quests</description>
    <score value="2"></score>
    <active value = "true" ></active>
    <conditions>
    	<classname value ="QuestsInRegionCompletedCondition"</classname>
    		<param value="80"?></value>
    </conditions>
  </achievement>
  
</achievements>
