=== joethompson1/Stendhal_TeamProject/data/conf/achievements.xsd
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="stendhal"
	xmlns:tns="http://www.example.org/zones" elementFormDefault="qualified"
	xmlns:Q1="stendhal">

	<element name="achievements" type="Q1:achievementGroup"></element>

	<complexType name="achievementGroup">
		<sequence>
			<element name="achievement" type="Q1:achievementType" minOccurs="0"
				maxOccurs="unbounded"></element>
		</sequence>
	</complexType>

	<complexType name="achievementType">
		<sequence>
			<element name="title" type="string"></element>
			<element name="description" type="string"></element>
			<element name="score" type="Q1:score"></element>
			<element name="active" type="string" ></element>
			<element name="conditions" type="Q1:conditions"></element>
		</sequence>
		<attribute name="identifier" type="string" use="required"></attribute>
	</complexType>

    <complexType name="score"
		<attribute name="value" type="integer"></attribute>
	</complexType>

	<complexType name="conditions"
	    <sequence>
			<element name="classname" minOccurs="0" maxOccurs="unbounded"></element>
			<element name="param" minOccurs="0" maxOccurs="unbounded"></element>
		</sequence>
		<attribute name="value" type="string"></attribute>
	</complexType>

</schema>

=== joethompson1/Stendhal_TeamProject/data/conf/achievements/obtainachievements.xml
<?xml version="1.0" encoding="UTF-8"?>
<achievements xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../achievements.xsd ">

  <achievement identifier="obtain.wish">
    <title>A wish came true</title>
    <description>Get an item from the wishing well</description>
    <score value="1"></score>
    <active value = "true" ></active>
    <conditions>
    	<classname value ="PlayerGotNumberOfItemsFromWellCondition"</classname>
    		<param value="0"?></value>
    </conditions>
  </achievement>
  
  <achievement identifier="obtain.harvest.vegetable">
    <title>Farmer</title>
    <description>Harvest 3 of all vegetables that grow in Faiumoni</description>
    <score value="1"></score>
    <active value = "true" ></active>
    <conditions>
    	<classname value ="PlayerGotNumberOfItemsFromWellCondition"</classname>
    		<param value="3"?></value>
    		<param value="carrot"?></value>
    		<param value="salad"?></value>
    		<param value="broccoli"?></value>
    		<param value="cauliflower"?></value>
    		<param value="leek"?></value>
    		<param value="onion"?></value>
    		<param value="courgette"?></value>
    		<param value="spinach"?></value>
    		<param value="collard"?></value>
    		<param value="garlic"?></value>
    		<param value="artichoke"?></value>
    </conditions>
  </achievement>
  
  <achievement identifier="obtain.fish">
    <title>Fisherman</title>
    <description>Catch 15 of each type of fish</description>
    <score value="2"></score>
    <active value = "true" ></active>
    <conditions>
    	<classname value ="PlayerGotNumberOfItemsFromWellCondition"</classname>
    		<param value="15"?></value>
    		<param value="char"?></value>
    		<param value="clownfish"?></value>
    		<param value="cod"?></value>
    		<param value="mackerel"?></value>
    		<param value="perch"?></value>
    		<param value="red lionfish"?></value>
    		<param value="roach"?></value>
    		<param value="surgeonfish"?></value>
    		<param value="trout"?></value>
    </conditions>
  </achievement>
  
  <achievement identifier="quest.special.collector">
    <title>Ultimate Collector</title>
    <description>Finish ultimate collector quest</description>
    <score value="5"></score>
    <active value = "true" ></active>
    <conditions>
    	<classname value ="PlayerGotNumberOfItemsFromWellCondition"</classname>
    		<param value="ultimate_collector"?></value>
    </conditions>
  </achievement>
 
  
</achievements>

=== joethompson1/Stendhal_TeamProject/data/conf/achievements/mithrilbourghenemyarmyachievement.xml
<?xml version="1.0" encoding="UTF-8"?>
<achievements xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../achievements.xsd ">

  <achievement identifier="quest.special.kill_enemy_army.0005">
    <title>Sergeant</title>
    <description>Finish Kill Enemy Army quest 5 times</description>
    <score value="2"></score>
    <active value = "true" ></active>
    <conditions>
    	<classname value ="QuestStateGreaterThanCondition"</classname>
    		<param value="kill_enemy_army"?></value>
    		<param value="3"?></value>
    		<param value="4"?></value>
    </conditions>
  </achievement>
  
  <achievement identifier="quest.special.kill_enemy_army.0025">
    <title>Major</title>
    <description>Finish Kill Enemy Army quest 25 times</description>
    <score value="5"></score>
    <active value = "true" ></active>
    <conditions>
    	<classname value ="QuestStateGreaterThanCondition"</classname>
    		<param value="kill_enemy_army"?></value>
    		<param value="3"?></value>
    		<param value="24"?></value>
    </conditions>
  </achievement>

  <achievement identifier="quest.special.kill_enemy_army.0050">
    <title>Major</title>
    <description>Finish Kill Enemy Army quest 50 times</description>
    <score value="5"></score>
    <active value = "true" ></active>
    <conditions>
    	<classname value ="QuestStateGreaterThanCondition"</classname>
    		<param value="kill_enemy_army"?></value>
    		<param value="3"?></value>
    		<param value="49"?></value>
    </conditions>
  </achievement>

  <achievement identifier="quest.special.kill_enemy_army.0100">
    <title>Field Marshal</title>
    <description>Finish Kill Enemy Army quest 100 times</description>
    <score value="5"></score>
    <active value = "true" ></active>
    <conditions>
    	<classname value ="QuestStateGreaterThanCondition"</classname>
    		<param value="kill_enemy_army"?></value>
    		<param value="3"?></value>
    		<param value="99"?></value>
    </conditions>
  </achievement>
  
</achievements>

=== joethompson1/Stendhal_TeamProject/data/conf/achievements/fightingachievements.xml
<?xml version="1.0" encoding="UTF-8"?>
<achievements xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../achievements.xsd ">

  <achievement identifier="fight.general.rats">
    <title>Rat Hunter</title>
    <description>Kill 15 rats</description>
    <score value="1"></score>
    <active value = "true" ></active>
    <conditions>
    	<classname value="PlayerHasKilledNumberOfCreaturesCondition"></class>
    		<param value="rat"?></param>
    		<param value="15"?></param>
    </conditions>
  </achievement>
  
  <achievement identifier="fight.general.exterminator">
    <title>Exterminator</title>
    <description>Kill 10 rats of each kind</description>
    <score value="2"></score>
    <active value = "true" ></active>
    <conditions>
    	<classname value="PlayerHasKilledNumberOfCreaturesCondition"></class>
    		<param value="10"?></param>
    		<param value="rat"?></param>
    		<param value="caverat"?></param>
    		<param value="razorrat"?></param>
    		<param value="venomrat"?></param>
    		<param value="zombie rat"?></param>
    		<param value="giantrat"?></param>
    		<param value="ratman"?></param>
    		<param value="ratwoman"?></param>
    		<param value="archrat"?></param>
    </conditions>
  </achievement>
  
  <achievement identifier="fight.general.deer">
    <title>Deer Hunter</title>
    <description>Kill 25 deer</description>
    <score value="1"></score>
    <active value = "true" ></active>
    <conditions>
    	<classname value="PlayerHasKilledNumberOfCreaturesCondition"></class>
    		<param value="deer"?></param>
    		<param value="25"?></param>
    </conditions>
  </achievement>
  
  <achievement identifier="fight.general.boars">
    <title>Boar Hunter</title>
    <description>Kill 20 boar</description>
    <score value="1"></score>
    <active value = "true" ></active>
    <conditions>
    	<classname value="PlayerHasKilledNumberOfCreaturesCondition"></class>
    		<param value="boar"?></param>
    		<param value="20"?></param>
    </conditions>
  </achievement>
  
  <achievement identifier="fight.general.bears">
    <title>Bear Hunter</title>
    <description>Kill 10 black bears, 10 bears and 10 babybears</description>
    <score value="1"></score>
    <active value = "true" ></active>
    <conditions>
    	<classname value="PlayerHasKilledNumberOfCreaturesCondition"></class>
    		<param value="10"?></param>
    		<param value="bear"?></param>
    		<param value="black bear"?></param>
    		<param value="babybear"?></param>
    </conditions>
  </achievement>
  
  <achievement identifier="fight.general.foxes">
    <title>Fox Hunter</title>
    <description>Kill 20 foxes</description>
    <score value="1"></score>
    <active value = "true" ></active>
    <conditions>
    	<classname value="PlayerHasKilledNumberOfCreaturesCondition"></class>
    		<param value="fox"?></param>
    		<param value="20"?></param>
    </conditions>
  </achievement>
  
  <achievement identifier="fight.general.foxes">
    <title>Fox Hunter</title>
    <description>Kill 20 foxes</description>
    <score value="1"></score>
    <active value = "true" ></active>
    <conditions>
    	<classname value="AndCondition"></class>
    		<classname value="PlayerHasKilledNumberOfCreaturesCondition"></class>
    			<param value="tiger"?></param>
    			<param value="30"?></param>
    		<classname value="PlayerHasKilledNumberOfCreaturesCondition"></class>
    			<param value="lion"?></param>
    			<param value="30"?></param>
    		<classname value="PlayerHasKilledNumberOfCreaturesCondition"></class>
    			<param value="elephant""?></param>
    			<param value="50"?></param>
    </conditions>
  </achievement>
  
  <achievement identifier="fight.general.ents">
    <title>Wood Cutter</title>
    <description>Kill 10 ents, 10 entwifes and 10 old ents</description>
    <score value="2"></score>
    <active value = "true" ></active>
    <conditions>
    	<classname value="PlayerHasKilledNumberOfCreaturesCondition"></class>
    		<param value="10"?></param>
    		<param value="ent"?></param>
    		<param value="entwife"?></param>
    		<param value="old ent"?></param>
    </conditions>
  </achievement>
  
  <achievement identifier="fight.special.rare">
    <title>Poacher</title>
    <description>Kill any rare creature</description>
    <score value="5"></score>
    <active value = "true" ></active>
    <conditions>
    	<classname value="KilledRareCreatureCondition"></class>
    </conditions>
  </achievement>
  
  <achievement identifier="fight.special.all">
    <title>Legend</title>
    <description>Kill all creatures solo</description>
    <score value="5"></score>
    <active value = "true" ></active>
    <conditions>
    	<classname value="KilledSoloAllCreaturesCondition"></class>
    </conditions>
  </achievement>
  
  <achievement identifier="fight.special.allshared">
    <title>Team Player</title>
    <description>Kill all creatures in a team</description>
    <score value="5"></score>
    <active value = "true" ></active>
    <conditions>
    	<classname value="KilledSharedAllCreaturesCondition"></class>
    </conditions>
  </achievement>
  
</achievements>
